---
galaxy_info:
  author: Kevin Brebanov
  description: Installs and configures OpenVPN
  company:
  license: BSD
  min_ansible_version: 1.9
  github_branch: master
  platforms:
  - name: Ubuntu
    versions:
    - trusty
    - xenial
  galaxy_tags:
  - networking
dependencies:
  - { role: palvarez89.easy_rsa3, when: openvpn_server and not openvpn_static }
