- hosts: raspberry
  vars:
    openvpn_server: true
    openvpn_redirect_gateway: true
    openvpn_remote_port: 8010
    openvpn_proto: tcp

  roles:
  - { role: security, become: yes }
  - { role: users, become: yes }
  - rpi-network-conf
  - rpi-power
  - palvarez89.openvpn_raspbian
