---
# tasks file for openvpn (Ubuntu specific)

- name: Install OpenVPN packages
  become: yes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - "{{ openvpn_packages }}"
  tags:
    - openvpn
