---
# tasks file for openvpn

- name: Include distribution specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  tags:
    - openvpn

- include: CentOS.yml
  when: ansible_distribution == "CentOS"
  tags:
    - openvpn

- include: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  tags:
    - openvpn

- include: Debian.yml
  when: ansible_distribution == "Debian"
  tags:
    - openvpn

- name: Create OpenVPN defaults configuration file
  become: yes
  template:
    src: openvpn.default.j2
    dest: /etc/default/openvpn
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution_release == "trusty"
  tags:
    - openvpn

- name: Create OpenVPN defaults configuration file
  become: yes
  template:
    src: openvpn.default.j2
    dest: /etc/default/openvpn
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution_release == "xenial"
  notify:
    - reload systemd
  tags:
    - openvpn

- name: Create OpenVPN client configuration file
  become: yes
  template:
    src: client.conf.j2
    dest: /etc/openvpn/client.conf
    owner: root
    group: root
    mode: 0640
  notify:
    - restart openvpn
  when: openvpn_client
  tags:
    - openvpn

- name: Create OpenVPN server configuration file
  become: yes
  template:
    src: server.conf.j2
    dest: /etc/openvpn/server/server.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart openvpn
  when: openvpn_server
  tags:
    - openvpn

- name: Create OpenVPN static key
  become: yes
  template:
    src: static.key.j2
    dest: "{{ openvpn_secret_file }}"
    owner: root
    group: root
    mode: 0600
  notify:
    - restart openvpn
  when: openvpn_static
  tags:
    - openvpn

- name: Copy DH to OpenVPN directory
  become: yes
  command: "cp {{ easy_rsa_key_dir }}/dh{{ easy_rsa_key_size }}.pem /etc/openvpn/server/"
  args:
    creates: "/etc/openvpn/server/dh{{ easy_rsa_key_size }}.pem"
  when: openvpn_server and not openvpn_static
  tags:
    - openvpn

- name: Copy CA certificate to OpenVPN directory
  become: yes
  command: "cp {{ easy_rsa_key_dir }}/ca.crt /etc/openvpn/server/"
  args:
    creates: /etc/openvpn/server/ca.crt
  when: openvpn_server and not openvpn_static
  tags:
    - openvpn

- name: Copy TLS server certificate to OpenVPN directory
  become: yes
  command: "cp {{ easy_rsa_key_dir }}/issued/{{ easy_rsa_key_name }}.crt /etc/openvpn/server/"
  args:
    creates: "/etc/openvpn/server/{{ easy_rsa_key_name }}.crt"
  when: openvpn_server and not openvpn_static
  tags:
    - openvpn

- name: Copy TLS server key to OpenVPN directory
  become: yes
  command: "cp {{ easy_rsa_key_dir }}/private/{{ easy_rsa_key_name }}.key /etc/openvpn/server/"
  args:
    creates: "/etc/openvpn/server/{{ easy_rsa_key_name }}.key"
  when: openvpn_server and not openvpn_static
  tags:
    - openvpn

- name: Copy CRL file to OpenVPN directory
  become: yes
  command: "cp {{ easy_rsa_key_dir }}/crl.pem /etc/openvpn/server"
  args:
    creates: /etc/openvpn/server/crl.pem
  when: openvpn_server and not openvpn_static
  tags:
    - openvpn

- name: Get contents of CA certificate
  become: yes
  slurp:
    src: /etc/openvpn/server/ca.crt
  register: ca_certificate
  when: openvpn_server and not openvpn_static
  tags:
    - openvpn

- name: Create client configuration template
  become: yes
  template:
    src: client.ovpn.j2
    dest: /etc/openvpn/client.ovpn
    owner: root
    group: root
    mode: 0644
  when: openvpn_server and not openvpn_static
  tags:
    - openvpn

- name: Ensure OpenVPN service is started and enabled on boot
  become: yes
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - "{{ openvpn_service_name }}"
    - openvpn-server@server
  tags:
    - openvpn
