---
galaxy_info:
  author: Pedro Alvarez
  description: Installs and configures easy-rsa333
  company:
  license: GPL
  min_ansible_version: 1.9
  github_branch: master
  platforms:
    - name: Debian
      versions:
        - stretch
  galaxy_tags:
    - system
dependencies: []
