---
# tasks file for easy_rsa
- include: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  tags:
    - easy_rsa

- include: Debian.yml
  when: ansible_distribution == "Debian"
  tags:
    - easy_rsa

- name: clone latest easy-rsa
  become: yes
  git:
    repo: https://github.com/OpenVPN/easy-rsa
    version: v3.0.3
    dest: "{{ easy_rsa_dir }}"

- name: Copy easyrsa files needed to /etc
  become: yes
  synchronize:
    src: "{{ easy_rsa_dir }}/easyrsa3/"
    dest: "{{ easy_rsa_ca_dir }}"
    recursive: yes
  delegate_to: "{{ inventory_hostname }}"

- name: Create CA directory
  become: yes
  command: mkdir {{ easy_rsa_ca_dir }}
  args:
    creates: "{{ easy_rsa_ca_dir }}"
  tags:
    - easy_rsa

- name: Create keys directory
  become: yes
  file:
    path: "{{ easy_rsa_key_dir }}"
    owner: root
    group: root
    mode: 0700
    state: directory
  tags:
    - easy_rsa


- name: Create vars configuration file
  become: yes
  template:
    src: vars.j2
    dest: "{{ easy_rsa_ca_dir }}/vars"
    owner: root
    group: root
    mode: 0644
  tags:
    - easy_rsa

#- export KEY_NAME= "{{ easy_rsa_key_name }}"

- shell: exit 1
- name: Prep the keys directory
  become: yes
  shell: ". ./vars; ./clean-all >/dev/null"
  args:
    chdir: "{{ easy_rsa_ca_dir }}"
    creates: "{{ easy_rsa_key_dir }}/index.txt"
  tags:
    - easy_rsa

- name: Generate Diffie-Hellman parameters
  become: yes
  shell: ". ./vars; ./build-dh >/dev/null"
  args:
    chdir: "{{ easy_rsa_ca_dir }}"
    creates: "{{ easy_rsa_key_dir }}/dh{{ easy_rsa_key_size }}.pem"
  tags:
    - easy_rsa

- name: Build CA
  become: yes
  shell: ". ./vars; ./pkitool --initca >/dev/null"
  args:
    chdir: "{{ easy_rsa_ca_dir }}"
    creates: "{{ easy_rsa_key_dir }}/ca.key"
  tags:
    - easy_rsa

- name: Generate server certificate and key
  become: yes
  shell: ". ./vars; ./pkitool --server {{ easy_rsa_key_name }} >/dev/null"
  args:
    chdir: "{{ easy_rsa_ca_dir }}"
    creates: "{{ easy_rsa_key_dir }}/{{ easy_rsa_key_name }}.key"
  tags:
    - easy_rsa

- name: Generate CRL file
  become: yes
  shell: '. ./vars; $OPENSSL ca -gencrl -out {{ easy_rsa_key_dir }}/crl.pem -config "$KEY_CONFIG"'
  environment:
    KEY_CN: ""
    KEY_OU: ""
    KEY_NAME: ""
    KEY_ALTNAMES: ""
  args:
    chdir: "{{ easy_rsa_ca_dir }}"
    creates: "{{ easy_rsa_key_dir }}/crl.pem"
  tags:
    - easy_rsa

- name: Generate client certificates and keys
  become: yes
  shell: ". ./vars; ./pkitool {{ item }} >/dev/null"
  args:
    chdir: "{{ easy_rsa_ca_dir }}"
    creates: "{{ easy_rsa_key_dir }}/{{ item }}.key"
  with_items:
    - "{{ easy_rsa_clients }}"
  tags:
    - easy_rsa
