---
- name: insert/update eth0 configuration for static ip in /etc/dhcpcd.conf
  blockinfile:
    dest: /etc/dhcpcd.conf
    block: |
        interface enxb827ebb5d9cd
        static ip_address=192.168.1.10/24
        static routers=192.168.1.1
        static domain_name_servers=192.168.1.1
  become: yes

- name: Set cron job to update dynamic dns
  copy:
    src: afraid-ddns
    dest: /etc/cron.hourly/afraid-ddns
    mode: 755
  become: yes

- name: Install fail2ban
  become: yes
  apt:
    name: fail2ban

- name: Configure fail2ban
  become: yes
  copy:
    src: sshd.conf
    dest: /etc/fail2ban/jail.d/sshd.conf
  register: fail2ban_configured

- name: Restart fail2ban
  become: yes
  service:
    name: fail2ban
    state: restarted
  when: fail2ban_configured.changed

# Following: http://readwrite.com/2014/04/10/raspberry-pi-vpn-tutorial-server-secure-web-browsing/
- lineinfile:
    dest: /etc/sysctl.conf
    regexp: "^#net.ipv4.ip_forward=1"
    line: "net.ipv4.ip_forward=1"
    backrefs: yes
  register: ip_forward_set
  become: yes

- shell: sysctl -p
  become: yes
  when: ip_forward_set.changed

# Iptables configuration
# Following: https://www.raspberrypi.org/forums/viewtopic.php?f=36&t=70594
- name: Install script to set firewall rules
  become: yes
  copy:
    src: firewall.sh
    dest: /usr/local/bin/firewall.sh
    mode: 755
  register: firewall_script_installed

- name: Make firewall rules run every boot
  become: yes
  lineinfile:
    dest: /etc/rc.local
    line: /usr/local/bin/firewall.sh
    insertbefore: "^exit 0"

- name: Set firewall rules
  become: yes
  shell: /usr/local/bin/firewall.sh
  when: firewall_script_installed.changed
