---
- name: Add quassel ppa
  apt_repository:
    repo: ppa:mamarley/quassel
- name: install quassel-core
  apt:
    name: quassel-core
    update_cache: yes

- name: install qt psql library needed
  apt:
    name: libqt5sql5-psql

#- name: postgresql backend
#  command: sudo -u quasselcore quasselcore --configdir=/var/lib/quassel --select-backend=PostgreSQL
